CREATE TABLE [dbo].[Summary_UnidadesSinTX] (
    [dateinfo]            DATETIME       NULL,
    [ingenioText]         VARCHAR (500)  NULL,
    [mobileid]            INT            NULL,
    [ingenio]             INT            NULL,
    [tipoplan]            VARCHAR (5)    NULL,
    [companyid]           INT            NULL,
    [compania]            VARCHAR (250)  NULL,
    [subflota]            VARCHAR (250)  NULL,
    [estado]              VARCHAR (50)   NULL,
    [placa]               VARCHAR (25)   NULL,
    [alias]               VARCHAR (150)  NULL,
    [dispositivo]         VARCHAR (50)   NULL,
    [tipodispositivo]     VARCHAR (50)   NULL,
    [imei]                VARCHAR (50)   NULL,
    [icc]                 VARCHAR (50)   NULL,
    [lineacelular]        VARCHAR (50)   NULL,
    [FechaUltimaTX]       DATETIME       NULL,
    [diasDif]             INT            NULL,
    [ubicacion]           VARCHAR (1000) NULL,
    [responsable]         VARCHAR (250)  NULL,
    [estadoactual]        VARCHAR (250)  NULL,
    [diagnostico]         VARCHAR (250)  NULL,
    [ticketid]            INT            NULL,
    [fechaultimagestion]  DATETIME       NULL,
    [comentarios]         VARCHAR (MAX)  NULL,
    [plataforma]          INT            NULL,
    [estadoUnidadesSinTX] INT            NULL
);

